import{a as E,S as w,i as n}from"./assets/vendor-BqJLIR3p.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))a(o);new MutationObserver(o=>{for(const t of o)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(o){const t={};return o.integrity&&(t.integrity=o.integrity),o.referrerPolicy&&(t.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?t.credentials="include":o.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(o){if(o.ep)return;o.ep=!0;const t=s(o);fetch(o.href,t)}})();const v="56322343-d60e20edbd0bfd9a78689fe35",I="https://pixabay.com/api/";async function d(r,e=1){const s={key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return(await E.get(I,{params:s})).data}const P=new w(".gallery a",{captionsData:"alt",captionDelay:250}),m=document.querySelector(".gallery"),u=document.getElementById("loader"),g=document.getElementById("load-more");function f(r){const e=r.map(({webformatURL:s,largeImageURL:a,tags:o,likes:t,views:i,comments:L,downloads:B})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${s}" alt="${o}" loading="lazy" />
        <div class="info">
          <p class="info-item"><b>Likes</b>${t}</p>
          <p class="info-item"><b>Views</b>${i}</p>
          <p class="info-item"><b>Comments</b>${L}</p>
          <p class="info-item"><b>Downloads</b>${B}</p>
        </div>
      </a>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",e),P.refresh()}function S(){m.innerHTML=""}function h(){u.classList.remove("is-hidden")}function p(){u.classList.add("is-hidden")}function y(){g.classList.remove("is-hidden")}function F(){g.classList.add("is-hidden")}const C=document.querySelector(".form"),k=document.getElementById("load-more");let c="",l=1;const b=15;C.addEventListener("submit",M);k.addEventListener("click",$);async function M(r){if(r.preventDefault(),c=r.target.elements.searchQuery.value.trim(),c===""){n.warning({message:"Please enter a search query!",position:"topRight",timeout:4e3,close:!0,animateInside:!1,backgroundColor:"#FFA000",messageColor:"#FFF",iconColor:"#FFF",progressBarColor:"#CC8000",theme:"dark"});return}l=1,S(),F(),h();try{const e=await d(c,l);if(e.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:5e3,close:!0,animateInside:!1,backgroundColor:"#EF4444",messageColor:"#FFF",iconColor:"#FFF",icon:"ico-error",progressBarColor:"#B91C1C",theme:"dark"});return}f(e.hits),e.totalHits>b&&y()}catch(e){n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight",timeout:5e3,close:!0,animateInside:!1,backgroundColor:"#EF4444",messageColor:"#FFF",iconColor:"#FFF",icon:"ico-error",progressBarColor:"#B91C1C",theme:"dark"}),console.error(e)}finally{p(),C.reset()}}async function $(){l+=1,F(),h();try{const r=await d(c,l);f(r.hits),q();const e=Math.ceil(r.totalHits/b);l>=e?n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:5e3,close:!0,animateInside:!1,backgroundColor:"#4E75FF",messageColor:"#FFF",iconColor:"#FFF",progressBarColor:"#2563EB",theme:"dark"}):y()}catch(r){n.error({title:"Error",message:"Failed to load more images.",position:"topRight",timeout:5e3,close:!0,animateInside:!1,backgroundColor:"#EF4444",messageColor:"#FFF",iconColor:"#FFF",icon:"ico-error",progressBarColor:"#B91C1C",theme:"dark"}),console.error(r)}finally{p()}}function q(){const r=document.querySelector(".gallery-item");if(r){const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
