import{a as E,S as w,i as s}from"./assets/vendor-CucEYOFD.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))i(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(o){if(o.ep)return;o.ep=!0;const r=a(o);fetch(o.href,r)}})();const k="56322343-d60e20edbd0bfd9a78689fe35",v="https://pixabay.com/api/";async function u(t,e=1){const a={key:k,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return(await E.get(v,{params:a})).data}const P=new w(".gallery a",{captionsData:"alt",captionDelay:250}),m=document.querySelector(".gallery"),g=document.getElementById("loader"),h=document.getElementById("load-more");function f(t){const e=t.map(({webformatURL:a,largeImageURL:i,tags:o,likes:r,views:n,comments:L,downloads:B})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${i}">
        <img class="gallery-image" src="${a}" alt="${o}" loading="lazy" />
        <div class="info">
          <p class="info-item"><b>Likes</b>${r}</p>
          <p class="info-item"><b>Views</b>${n}</p>
          <p class="info-item"><b>Comments</b>${L}</p>
          <p class="info-item"><b>Downloads</b>${B}</p>
        </div>
      </a>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",e),P.refresh()}function S(){m.innerHTML=""}function p(){g.classList.remove("is-hidden")}function y(){g.classList.add("is-hidden")}function F(){h.classList.remove("is-hidden")}function d(){h.classList.add("is-hidden")}const C=document.querySelector(".form"),M=document.getElementById("load-more");let c="",l=1;const b=15;C.addEventListener("submit",R);M.addEventListener("click",$);async function R(t){if(t.preventDefault(),c=t.target.elements.searchQuery.value.trim(),c===""){s.warning({message:"Please enter a search query!",position:"topRight",timeout:4e3,close:!0,backgroundColor:"#FFA000",messageColor:"#FFF",iconColor:"#FFF",progressBarColor:"#CC8000",theme:"dark"});return}l=1,S(),d(),p();try{const e=await u(c,l);if(e.hits.length===0){s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:5e3,close:!0,backgroundColor:"#EF4444",messageColor:"#FFF",iconColor:"#FFF",progressBarColor:"#B91C1C",theme:"dark"});return}f(e.hits),e.totalHits<=b?(d(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:5e3,close:!0,backgroundColor:"#4E75FF",messageColor:"#FFF",iconColor:"#FFF",progressBarColor:"#2563EB",theme:"dark"})):F()}catch(e){s.error({message:"Something went wrong. Please try again later.",position:"topRight",backgroundColor:"#EF4444",messageColor:"#FFF",theme:"dark"}),console.error(e)}finally{y(),C.reset()}}async function $(){l+=1,d(),p();try{const t=await u(c,l);f(t.hits),q();const e=Math.ceil(t.totalHits/b);l>=e?s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:5e3,close:!0,backgroundColor:"#4E75FF",messageColor:"#FFF",iconColor:"#FFF",progressBarColor:"#2563EB",theme:"dark"}):F()}catch(t){s.error({message:"Failed to load more images.",position:"topRight",backgroundColor:"#EF4444",messageColor:"#FFF",theme:"dark"}),console.error(t)}finally{y()}}function q(){const t=document.querySelector(".gallery-item");if(t){const{height:e}=t.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
